// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNQydgp4IQhLITVoa_v8N0vU2k1YJT_FQ',
    appId: '1:265580445:web:1ab33489e32b196dc68974',
    messagingSenderId: '265580445',
    projectId: 'mynotes-44cd0',
    authDomain: 'mynotes-44cd0.firebaseapp.com',
    storageBucket: 'mynotes-44cd0.appspot.com',
    measurementId: 'G-707VLVKTWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGTwjK7RCmASwwZ2TANP9WJc3XChGPHag',
    appId: '1:265580445:android:816e060d10183970c68974',
    messagingSenderId: '265580445',
    projectId: 'mynotes-44cd0',
    storageBucket: 'mynotes-44cd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByj4q-rKcuyXbhr3C-Fl5DeSbIoxS5HmY',
    appId: '1:265580445:ios:dc730c1b54816d06c68974',
    messagingSenderId: '265580445',
    projectId: 'mynotes-44cd0',
    storageBucket: 'mynotes-44cd0.appspot.com',
    iosBundleId: 'com.mynotes.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByj4q-rKcuyXbhr3C-Fl5DeSbIoxS5HmY',
    appId: '1:265580445:ios:b099145bdacc41aac68974',
    messagingSenderId: '265580445',
    projectId: 'mynotes-44cd0',
    storageBucket: 'mynotes-44cd0.appspot.com',
    iosBundleId: 'com.mynotes.mynotes.RunnerTests',
  );
}
